//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.UI.Web.MVC.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PM.UI.Web.MVC.Resources.Views.Home.Index.fr", typeof(Index_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répondez aux questions.
        /// </summary>
        internal static string Answer_the_questions {
            get {
                return ResourceManager.GetString("Answer the questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quelques exemples de texte rapides pour s&apos;appuyer sur le titre de la carte et constituer l&apos;essentiel du contenu de la carte..
        /// </summary>
        internal static string CardText {
            get {
                return ResourceManager.GetString("CardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez votre sous-thème.
        /// </summary>
        internal static string Choose_your_subtheme {
            get {
                return ResourceManager.GetString("Choose your subtheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maison.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous prêt à faire entendre votre voix et à créer un réel changement ? Entrez ensuite dans le monde de StemConnect, où nous donnons aux jeunes comme vous les moyens d&apos;exprimer leurs opinions et d&apos;influencer le monde qui les entoure..
        /// </summary>
        internal static string HomeText {
            get {
                return ResourceManager.GetString("HomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laissez un massage personnel.
        /// </summary>
        internal static string Leave_a_personal_message {
            get {
                return ResourceManager.GetString("Leave a personal message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adhérer maintenant.
        /// </summary>
        internal static string Neem_nu_deel {
            get {
                return ResourceManager.GetString("Neem nu deel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répéter.
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu&apos;est-ce que tu attends ?.
        /// </summary>
        internal static string Waar_wacht_je_op_ {
            get {
                return ResourceManager.GetString("Waar wacht je op?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenu.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
