//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.UI.Web.MVC.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_nl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_nl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PM.UI.Web.MVC.Resources.Views.Home.Index.nl", typeof(Index_nl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beantwoord de vragen.
        /// </summary>
        internal static string Answer_the_questions {
            get {
                return ResourceManager.GetString("Answer the questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een korte voorbeeldtekst om voort te bouwen op de kaarttitel en het grootste deel van de inhoud van de kaart te vormen..
        /// </summary>
        internal static string CardText {
            get {
                return ResourceManager.GetString("CardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies uw subthema.
        /// </summary>
        internal static string Choose_your_subtheme {
            get {
                return ResourceManager.GetString("Choose your subtheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ben je klaar om je stem te laten horen en echte verandering teweeg te brengen? Stap dan binnen in de wereld van StemConnect, waar we jongeren zoals jij de kracht geven om hun mening te uiten en invloed uit te oefenen op de wereld om hen heen..
        /// </summary>
        internal static string HomeText {
            get {
                return ResourceManager.GetString("HomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een korte tekst die hier in de plaats zal komen..
        /// </summary>
        internal static string item2textbox {
            get {
                return ResourceManager.GetString("item2textbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLACEHOLDER.
        /// </summary>
        internal static string item2textboxtitel {
            get {
                return ResourceManager.GetString("item2textboxtitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laat een persoonlijke bericht achter.
        /// </summary>
        internal static string Leave_a_personal_message {
            get {
                return ResourceManager.GetString("Leave a personal message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neem nu deel.
        /// </summary>
        internal static string Neem_nu_deel {
            get {
                return ResourceManager.GetString("Neem nu deel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doe het opnieuw .
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Waar_wacht_je_op {
            get {
                return ResourceManager.GetString("Waar wacht je op", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waar wacht je op ?.
        /// </summary>
        internal static string Waar_wacht_je_op_ {
            get {
                return ResourceManager.GetString("Waar wacht je op?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welkom.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
